baseURL: https://simpleprivacy.fr/
languageCode: fr-FR
defaultContentLanguage: fr
title: SimplePrivacy
theme: "WonderMod"
copyright: '[CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/deed.fr)'
enableGitInfo: true

enableRobotsTXT: false
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: SimplePrivacy
  description: "Une approche plus simple pour récupérer votre vie privée en ligne."
  keywords: [Privacy, Sécurité, Vie Privée]
  author: samsepi0l
  # author: ["Me", "You"] # multiple authors
  images: ["/simpleprivacy_banner.jpg"]
  DateFormat: "2 January 2006"
  defaultTheme: dark # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  assets:
    disableHLJS: true # to disable highlight.js
    disableFingerprinting: true
    favicon: "/favicon.ico"
    faviconSVG: "/favicon.svg"
    appleTouchIcon: "/apple-touch-icon.png"
    maskIcon: "/mask-icon.svg"
    webmanifest: "/manifest.webmanifest"
    themeColor: "#1f2125"
    msapplicationTileColor: "#1f2125"
    maskIconColor: "#a2adc0"

  label:
    text: "Accueil"
    icon: "/favicon-32x32.png"
    iconHeight: 32

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: SimplePrivacy.fr
    subtitle: "Une approche plus simple pour récupérer votre vie privée en ligne."
    # imageUrl: "simpleprivacy_logo_mono.png"
    # imageWidth: 100
    # imageHeight: 100
    # imageTitle: my image
    buttons:
      #- name: Commencez ici
      #  url: evidence-based-security
      - name: À propos
        url: about
      - name: Politique de confidentialité
        url: privacy
      - name: Faites un don
        url: donation

  # home-info mode
  homeInfoParams:
    Title: "Hello friend \U0001F44B"
    Content: Une approche plus simple pour récupérer votre vie privée en ligne

  socialIcons:
    - name: github
      url: "https://github.com/d4rklynk/simpleprivacy.fr"
    - name: matrix
      url: "https://matrix.to/#/@samsepi0l:arcticfoxes.net"
    - name: mastodon
      url: "https://infosec.exchange/@samsepi0l"
    - name: twitter
      url: "https://twitter.com/samsepi0l753"
    - name: bluesky
      url: "https://bsky.app/profile/samsepi0l.dev"
    - name: email
      url: "mailto:contact@simpleprivacy.fr"
    - name: pgpkey
      url: pub-key.txt
    - name: rss
      url: /index.xml

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page

  editPost:
    URL: "https://github.com/d4rklynk/simpleprivacy.fr/tree/main/content"
    Text: "Suggérer un changement" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "summary"]

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

menu:
  main:
    - identifier: Les basiques
      name: Les basiques
      url: /basiques/
      weight: 10
    - identifier: Les fiches
      name: Les fiches
      url: /fiches/
      weight: 20
    - identifier: Les alternatives
      name: Les alternatives
      url: /alternatives/
      weight: 30
    - identifier: Search
      name: Rechercher
      url: /search/
      weight: 40
    - identifier: Blog
      name: Blog
      url: https://samsepi0l.dev
      weight: 50
    - identifier: Services
      name: Services
      url: https://services.simpleprivacy.fr
      weight: 60


# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    style: dracula
    noClasses: false
    guessSyntax: true
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    disable: true
    respectDoNotTrack: true
    useSessionStorage: false
  instagram:
    disable: true
    simple: false
  twitter:
    disable: false
    enableDNT: true
    simple: false
  vimeo:
    disable: false
    enableDNT: true
    simple: false
  youtube:
    disable: false
    privacyEnhanced: true
