baseURL: http://samsepi0l.ovh/
languageCode: fr-fr
title: samsepi0l
theme: "PaperMod"
copyright: '[CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/deed.fr)'

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: false # to enable google analytics, opengraph, twitter-cards and schema.
  title: samsepi0l
  description: "samsepi0l description"
  keywords: [Privacy, Sécurité, Vie Privée]
  author: samsepi0l
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Accueil"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: samsepi0l.ovh
    subtitle: "Une approche plus simple pour récuperer votre vie privée en ligne"
    # imageUrl: "<img location>"
    # imageWidth: 120
    # imageHeight: 120
    # imageTitle: my image
    buttons:
      - name: A propos
        url: about
      - name: Politique de confidentialité
        url: privacy

  # home-info mode
  homeInfoParams:
    Title: "Hello friend \U0001F44B"
    Content: Une approche plus simple pour récuperer votre vie privée en ligne

  socialIcons:
    - name: github
      url: "https://github.com/d4rklynk/samsepi0l.ovh"
    - name: matrix
      url: "https://matrix.to/#/@samsepi0l:arcticfoxes.net"
    - name: rss
      url: /index.xml

  analytics:
    google:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page

  editPost:
    URL: "https://github.com/d4rklynk/samsepi0l.ovh/content"
    Text: "Suggérer un changement" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "summary", "content"]

menu:
  main:
    - identifier: Les basiques
      name: Les basiques
      url: /basics/
      weight: 10
    - identifier: Les fiches
      name: Les fiches
      url: /fiches/
      weight: 20
    - identifier: Les alternatives
      name: Les alternatives
      url: /alternatives/
      weight: 30

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

privacy:
  disqus:
    disable: true
  instagram:
    disable: true
    simple: false
  twitter:
    disable: false
    enableDNT: true
    simple: false
  vimeo:
    disable: false
    enableDNT: true
    simple: false
  youtube:
    disable: false
    privacyEnhanced: true
