[build.environment]
  HUGO_VERSION = "0.113.0"

[context.production]
  command = "hugo -b $DEPLOY_PRIME_URL"
[context.deploy-preview]
  command = "sed -i 's/! Content-Security-Policy//g' static/_headers && hugo --minify -b $DEPLOY_PRIME_URL"
