[build.environment]
  HUGO_VERSION = "0.138.0"
  NODE_ENV = "production"
  GO_VERSION = "1.23.3"
  TZ = "Europe/Paris"  # Set to preferred timezone

[context.deploy-preview]
  command = "sed -i 's/! Content-Security-Policy//g' static/_headers && hugo --minify -b $DEPLOY_PRIME_URL"